#!/bin/bash
[[ -z "$INFO_LEVEL" ]] && source ./bits/bootstrap/logging

notify "  -- Running $CMD in DOCKER container $NAME ($VERSION)"
BUILD_OUTPUT=${LAUNCHER_DIR}/docker_build.log
TS=$(date +"%Y%m%d%H%M%S")
CID_FILE=${LAUNCHER_DIR}/$NAME-$VERSION-$TS.cid

(cd ${LAUNCHER_DIR} && IGNORE=$(docker run $DOCKER_ARGS --cidfile $CID_FILE $DOCKER_IMAGE $CMD >> $BUILD_OUTPUT 2>&1))
ERROR="Error running $CMD in DOCKER container $NAME ($VERSION), due to ..." ./bits/bootstrap/failonerrors $? $BUILD_OUTPUT
[ $? -ne 0 ] && exit 1

CONTAINER=$(cat $CID_FILE)

debug "  -- Commiting resulting container to image $NAME:$VERSION"
DOCKER_ID=$(docker commit $CONTAINER $NAME:$VERSION)
[ $? -ne 0 ] && exit 1

IGNORE=$((docker rm -f $CONTAINER && rm $CID_FILE) >> $BUILD_OUTPUT 2>&1)
ERROR="Error stopping DOCKER container $NAME-$VERSION running $CMD" ./bits/bootstrap/failonerrors $? $BUILD_OUTPUT
[ $? -ne 0 ] && exit 1

NAME=$NAME VERSION=latest DOCKER_ID=$DOCKER_ID ./bits/docker/tag
[ $? -ne 0 ] && exit 1

