#!/bin/bash
source ./submodules/bootstrap/logging

notify "  -- Building DOCKER container $NAME (${LAUNCHER_DIR}/Dockerfile)"
if [[ "$LOGLEVEL" -le "$DEBUG_LEVEL" ]]; then
  DOCKER_OUTPUT=${LAUNCHER_DIR}/docker_build.log
else
  DOCKER_OUTPUT=/dev/null
fi

(cd ${LAUNCHER_DIR} && DOCKER_ERRORS=$(docker build -t $NAME . 2>&1 > $DOCKER_OUTPUT))
debug_all $DOCKER_OUTPUT

ERRORS=$DOCKER_ERRORS \
  MSG="Error building DOCKER container $NAME (${LAUNCHER_DIR}/Dockerfile), due to ..." \
  ./submodules/bootstrap/exitif
