#!/bin/bash
printf "%b" "#!/bin/bash
source logging
CONTAINER_ID=\`${DIR}/running\`
if [[ \"\$CONTAINER_ID\" == \"\" ]]; then
  notify 'Starting ${NAME} container...'
  $DIR/start
else
  debug '${NAME} container already running'
fi
" > $DIR/idempot

chmod 755 $DIR/idempot
OWNER=${OWNER-$USER}
chown $OWNER $DIR/idempot