#!/bin/bash
printf "%b" "#!/bin/bash
CONTAINER_ID=\`cat ${DIR}/container.pid 2> /dev/null\`
if [[ \"\$CONTAINER_ID\" == \"\" ]]; then
  echo 'Starting ${NAME} container...'
  $DIR/start
else
  echo '${NAME} container already running'
fi
" > $DIR/idempot

chmod 755 $DIR/idempot