#!/bin/bash
if [[ -e ./bits/bootstrap/logging ]]; then
  source ./bits/bootstrap/logging
else
  source logging
fi

VERSION=${VERSION-latest}
debug "  -- Looking up image $NAME $VERSION"
docker images $NAME | grep $VERSION | awk '{ print $3 }'
