#!/bin/bash

#-----------
# Configurations
#-----------

DOCKER_SUPPORT_LXC=${DOCKER_SUPPORT_LXC-false}

#-----------
# Install Script
#-----------


mkdir -p /var/apps/docker/

if [[ ! -e "/var/apps/docker/ufw.done" ]]; then
  sed -i 's|DEFAULT_FORWARD_POLICY="DROP"|DEFAULT_FORWARD_POLICY="ACCEPT"|g' /etc/default/ufw
  ufw reload
  ufw allow 4243/tcp
  touch "/var/apps/docker/ufw.done"
fi

if [[ "`which docker`" == "" ]]; then
  apt-get update
  apt-get install -y docker.io
  ln -sf /usr/bin/docker.io /usr/local/bin/docker
  sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io

  [ -e /usr/lib/apt/methods/https ] || {
    apt-get update
    apt-get install -y apt-transport-https
  }

  apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9

  apt-get install -y curl
  curl -s https://get.docker.io/ubuntu/ | sh
fi

if [[ "$DOCKER_SUPPORT_LXC" == true ]]; then
  apt-get install -y lxc
  cp ./submodules/docker/files/conf /etc/default/docker
fi

if [[ "`service docker status | grep process`" == "" ]]; then
  service docker restart
fi





