#!/bin/bash
printf "%b" "#!/bin/bash
ID=\${ID-\`${DIR}/running\`}
if [[ \"\$ID\" == '' ]]; then
  echo ''
else
  IP=\$(docker inspect \$ID | python -c 'import json,sys;obj=json.load(sys.stdin);print obj[0][\"NetworkSettings\"][\"IPAddress\"]')
  echo \"\$IP\"
fi
" > $DIR/ip

chmod 755 $DIR/ip