#!/bin/bash
printf "%b" "#!/bin/bash
CONTAINER_ID=\`cat ${DIR}/container.pid 2> /dev/null\`
if [[ \"\$CONTAINER_ID\" == \"\" ]]; then
  $DIR/start
else
  $DIR/stop
  $DIR/start
fi
" > $DIR/restart

chmod 755 $DIR/restart