#!/bin/bash
printf "%b" "#!/bin/bash
CONTAINER_ID=\$(docker ps --no-trunc | grep $NAME | awk '{print \$1}')
if [[ \"\$CONTAINER_ID\" == \"\" ]]; then
  $DIR/start
else
  $DIR/stop
  $DIR/start
fi
" > $DIR/restart

chmod 755 $DIR/restart