#!/bin/bash
source ./bits/bootstrap/logging

export DOCKER_ASSETS_DIR=${DOCKER_ASSETS_DIR-./assets/dockerimages}
IMAGE_NAME=${IMAGE_NAME-$NAME:$VERSION}
DOCKER_IMAGE_FILE=$DOCKER_ASSETS_DIR/${NAME}.${VERSION}.tar
LATEST_IMAGE_FILE=$DOCKER_ASSETS_DIR/${NAME}.latest.tar
SAVE_OUTPUT=${LAUNCHER_DIR}/docker_save.log
BUILD_OUTPUT=${LAUNCHER_DIR}/docker_build.log
OWNER=${OWNER-$USER}

if [[ -e $BUILD_OUTPUT ]] && [[ ! -z `tail -n 4 $BUILD_OUTPUT | grep "Using cache"` ]] && [[ -e $DOCKER_IMAGE_FILE.gz ]]; then
  notify "  -- No changes to $IMAGE_NAME, not overwriting $DOCKER_IMAGE_FILE.gz"

elif [[ "$DOCKER_ASSETS_SERVER" != "local" ]]; then
  DOCKER_ASSETS_DIR=/tmp OWNER=$OWNER LAUNCHER_DIR=$LAUNCHER_DIR NAME=$NAME VERSION=$VERSION ./bits/docker/save
  [ $? -ne 0 ] && exit 1
  notify "  -- Uploading /tmp/${NAME}.${VERSION}.tar.gz to $DOCKER_ASSETS_DIR/${NAME}.${VERSION}.tar"
  scp /tmp/${NAME}.${VERSION}.tar.gz $DOCKER_ASSETS_DIR/${NAME}.${VERSION}.tar.gz

else
  OWNER=$OWNER ./bits/bootstrap/mkdir DOCKER_ASSETS_DIR
  [ $? -ne 0 ] && exit 1
  notify "  -- Saving $IMAGE_NAME to $DOCKER_IMAGE_FILE.gz"

  debug "  -- Creating $DOCKER_IMAGE_FILE"
  SCRIPT_OUTPUT=$(docker save -o $DOCKER_IMAGE_FILE $IMAGE_NAME > $SAVE_OUTPUT 2>&1)
  ERROR="Unable to save $IMAGE_NAME to $DOCKER_IMAGE_FILE due to ..." ./bits/bootstrap/failonerrors $? $SAVE_OUTPUT
  [ $? -ne 0 ] && exit 1

  debug "  -- Compressing to $DOCKER_IMAGE_FILE.gz"
  rm -f $DOCKER_IMAGE_FILE.gz
  SCRIPT_OUTPUT=$(gzip $DOCKER_IMAGE_FILE > $SAVE_OUTPUT 2>&1)
  ERROR="Unable to gzip $DOCKER_IMAGE_FILE due to ..." ./bits/bootstrap/failonerrors $? $SAVE_OUTPUT
  [ $? -ne 0 ] && exit 1

  OWNER=$OWNER ./bits/bootstrap/touch $DOCKER_IMAGE_FILE.gz
  debug "  -- DONE, Saving $IMAGE_NAME to $DOCKER_IMAGE_FILE.gz"
fi
