#!/bin/bash
printf "%b" "#!/bin/bash
CONTAINER_ID=\`cat ${DIR}/container.pid 2> /dev/null\`
if [[ \"\$CONTAINER_ID\" == '' ]]; then
  echo '$NAME container already stopped, nothing to do.'
else
  echo 'Stopping $NAME...'
  docker stop \$CONTAINER_ID 2>1 >> /dev/null
  if [[ \"$HOST\" != \"\" ]]; then
    sed -i \"s|.*$HOST||g\" /etc/hosts
  fi
  rm -f ${DIR}/container.pid
  echo 'DONE Stopping $NAME.'
fi
" > $DIR/stop

chmod 755 $DIR/stop