#!/bin/bash
CONTAINERS=$(docker ps -a -q)

if [[ "$CONTAINERS" != "" ]]; then
  echo "Removing all stopped containers"
  docker rm $CONTAINERS > /dev/null 2>&1
else
  echo "No containers to purge"
fi
