#!/bin/bash
CONTAINERS=$(docker ps -a -q)

if [[ "$CONTAINERS" != "" ]]; then
  echo "Purging all running containers"
  echo "  -- Stopping all containers"
  docker stop $CONTAINERS
  echo "  -- Removing all containers"
  docker rm $CONTAINERS
else
  echo "No running containers to purge"
fi
